bianchi2_error_mod Module Reference
bianchi2_error_mod Module Reference
Functions/Subroutines
subroutine, public bianchi2_error (error_code, procedure, comment_add, comment_out, halt_in)
Variables
integer, parameter BIANCHI2_ERROR_NUM = 9
integer, parameter, public BIANCHI2_ERROR_NONE = 0
integer, parameter, public BIANCHI2_ERROR_INIT = 1
integer, parameter, public BIANCHI2_ERROR_NOT_INIT = 2
integer, parameter, public BIANCHI2_ERROR_INIT_FAIL = 3
integer, parameter, public BIANCHI2_ERROR_MEM_ALLOC_FAIL = 4
integer, parameter, public BIANCHI2_ERROR_SIM_PARAM_INVALID = 5
integer, parameter, public BIANCHI2_ERROR_SIM_NARG = 6
integer, parameter, public BIANCHI2_ERROR_SKY_NUM_FAIL = 7
integer, parameter, public BIANCHI2_ERROR_TMPLFIT_FAIL = 8
character(len=S2_STRING_LEN),
dimension(bianchi2_error_num),
parameter error_comment = (/ 'No error ', 'Attempt to initialise object that has already been initialised ', 'Object not initialised ', 'Object initialisation failed ', 'Memory allocation failed ', 'Invalid simulation parameter ', 'Invalid number of command line parameters ', 'Numerical routine failed ', 'Template fitting failed ' /)
logical, dimension(bianchi2_error_num),
parameter halt_default = (/ .false., .true., .true., .true., .true., .true., .true., .true., .true. /)
Function/Subroutine Documentation
subroutine,public bianchi2_error_mod::bianchi2_error (integer,intent(in) error_code, character(len=*),intent(in),optional procedure, character(len=*),intent(in),optional comment_add, character(len=*),intent(inout),optional comment_out, logical,intent(in),optional halt_in)
Definition at line 109 of file bianchi2_error_mod.f90.
References error_comment, and halt_default.
Referenced by bianchi2_sim(), bianchi2_sky_mod::bianchi2_sky_compute_alm(), bianchi2_sky_mod::bianchi2_sky_compute_map(), bianchi2_sky_mod::bianchi2_sky_free(), bianchi2_sky_mod::bianchi2_sky_get_alm(), bianchi2_sky_mod::bianchi2_sky_init(), bianchi2_sky_mod::bianchi2_sky_init_alm(), bianchi2_sky_mod::bianchi2_sky_rotate(), bianchi2_sky_mod::bianchi2_sky_write(), and bianchi2_sky_mod::get_results().
Variable Documentation
integer,parameter,public bianchi2_error_mod::BIANCHI2_ERROR_INIT = 1
Definition at line 37 of file bianchi2_error_mod.f90.
Referenced by bianchi2_sky_mod::bianchi2_sky_init(), and bianchi2_sky_mod::bianchi2_sky_init_alm().
integer,parameter,public bianchi2_error_mod::BIANCHI2_ERROR_INIT_FAIL = 3
Definition at line 37 of file bianchi2_error_mod.f90.
integer,parameter,public bianchi2_error_mod::BIANCHI2_ERROR_MEM_ALLOC_FAIL = 4
Definition at line 37 of file bianchi2_error_mod.f90.
Referenced by bianchi2_sky_mod::bianchi2_sky_init(), bianchi2_sky_mod::bianchi2_sky_init_alm(), and bianchi2_sky_mod::bianchi2_sky_rotate().
integer,parameter,public bianchi2_error_mod::BIANCHI2_ERROR_NONE = 0
Definition at line 37 of file bianchi2_error_mod.f90.
integer,parameter,public bianchi2_error_mod::BIANCHI2_ERROR_NOT_INIT = 2
Definition at line 37 of file bianchi2_error_mod.f90.
Referenced by bianchi2_sky_mod::bianchi2_sky_compute_alm(), bianchi2_sky_mod::bianchi2_sky_compute_map(), bianchi2_sky_mod::bianchi2_sky_free(), bianchi2_sky_mod::bianchi2_sky_get_alm(), bianchi2_sky_mod::bianchi2_sky_get_sky(), bianchi2_sky_mod::bianchi2_sky_rotate(), and bianchi2_sky_mod::bianchi2_sky_write().
integer,parameter bianchi2_error_mod::BIANCHI2_ERROR_NUM = 9
Definition at line 35 of file bianchi2_error_mod.f90.
integer,parameter,public bianchi2_error_mod::BIANCHI2_ERROR_SIM_NARG = 6
Definition at line 37 of file bianchi2_error_mod.f90.
Referenced by bianchi2_sim().
integer,parameter,public bianchi2_error_mod::BIANCHI2_ERROR_SIM_PARAM_INVALID = 5
Definition at line 37 of file bianchi2_error_mod.f90.
Referenced by bianchi2_sim().
integer,parameter,public bianchi2_error_mod::BIANCHI2_ERROR_SKY_NUM_FAIL = 7
Definition at line 37 of file bianchi2_error_mod.f90.
Referenced by bianchi2_sky_mod::get_results().
integer,parameter,public bianchi2_error_mod::BIANCHI2_ERROR_TMPLFIT_FAIL = 8
Definition at line 37 of file bianchi2_error_mod.f90.
character(len=S2_STRING_LEN),dimension(bianchi2_error_num),parameter bianchi2_error_mod::error_comment = (/ 'No error ', 'Attempt to initialise object that has already been initialised ', 'Object not initialised ', 'Object initialisation failed ', 'Memory allocation failed ', 'Invalid simulation parameter ', 'Invalid number of command line parameters ', 'Numerical routine failed ', 'Template fitting failed ' /)
Definition at line 52 of file bianchi2_error_mod.f90.
Referenced by bianchi2_error().
logical,dimension(bianchi2_error_num),parameter bianchi2_error_mod::halt_default = (/ .false., .true., .true., .true., .true., .true., .true., .true., .true. /)
Definition at line 67 of file bianchi2_error_mod.f90.
Referenced by bianchi2_error().