bianchi2_globaldata_mod Module Reference
bianchi2_globaldata_mod Module Reference
Variables
integer, parameter b2gd_ntmax = 101
integer, parameter b2gd_nvars = 4
integer b2gd_it
integer b2gd_nt
real, dimension(b2gd_ntmax) b2gd_treal
real, dimension(b2gd_ntmax) b2gd_xreal
real(s2_dp) b2gd_Omega_matter
real(s2_dp) b2gd_Omega_Lambda
real(s2_dp) b2gd_alpha
real(s2_dp) b2gd_Bianchi_h
real(s2_dp) b2gd_RH_start
real(s2_dp) b2gd_ze
real(s2_dp) b2gd_theta_0
real(s2_dp) b2gd_phi_0
real(s2_dp), dimension(b2gd_nvars,
b2gd_ntmax) b2gd_xarr
real(s2_dp), dimension(b2gd_ntmax) b2gd_tarr
real(s2_dp) b2gd_tstop
real(s2_dp) b2gd_deltat
Variable Documentation
real(s2_dp) bianchi2_globaldata_mod::b2gd_alpha
Definition at line 33 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::bianchi2_sky_init(), bianchi2_sky_mod::bianchi2_sky_init_alm(), bianchi2_sky_mod::F1r(), and bianchi2_sky_mod::fcn().
real(s2_dp) bianchi2_globaldata_mod::b2gd_Bianchi_h
Definition at line 33 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::bianchi2_sky_init(), and bianchi2_sky_mod::bianchi2_sky_init_alm().
real(s2_dp) bianchi2_globaldata_mod::b2gd_deltat
Definition at line 44 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::get_results(), and bianchi2_sky_mod::out().
integer bianchi2_globaldata_mod::b2gd_it
Definition at line 23 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::get_results(), and bianchi2_sky_mod::out().
integer bianchi2_globaldata_mod::b2gd_nt
Definition at line 24 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::get_results(), and bianchi2_sky_mod::out().
integer,parameter bianchi2_globaldata_mod::b2gd_ntmax = 101
Definition at line 20 of file bianchi2_globaldata_mod.f90.
integer,parameter bianchi2_globaldata_mod::b2gd_nvars = 4
Definition at line 21 of file bianchi2_globaldata_mod.f90.
real(s2_dp) bianchi2_globaldata_mod::b2gd_Omega_Lambda
Definition at line 32 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::bianchi2_sky_init(), bianchi2_sky_mod::bianchi2_sky_init_alm(), bianchi2_sky_mod::F1r(), and bianchi2_sky_mod::fcn().
real(s2_dp) bianchi2_globaldata_mod::b2gd_Omega_matter
Definition at line 31 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::bianchi2_sky_init(), bianchi2_sky_mod::bianchi2_sky_init_alm(), and bianchi2_sky_mod::F1r().
real(s2_dp) bianchi2_globaldata_mod::b2gd_phi_0
Definition at line 36 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::bianchi2_sky_init().
real(s2_dp) bianchi2_globaldata_mod::b2gd_RH_start
Definition at line 34 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::bianchi2_sky_init(), bianchi2_sky_mod::bianchi2_sky_init_alm(), bianchi2_sky_mod::fcn(), and bianchi2_sky_mod::get_results().
real(s2_dp),dimension(b2gd_ntmax) bianchi2_globaldata_mod::b2gd_tarr
Definition at line 39 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::get_results(), and bianchi2_sky_mod::out().
real(s2_dp) bianchi2_globaldata_mod::b2gd_theta_0
Definition at line 36 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::bianchi2_sky_init(), bianchi2_sky_mod::bianchi2_sky_init_alm(), and bianchi2_sky_mod::fcn().
real,dimension(b2gd_ntmax) bianchi2_globaldata_mod::b2gd_treal
Definition at line 26 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::get_results().
real(s2_dp) bianchi2_globaldata_mod::b2gd_tstop
Definition at line 43 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::get_results(), and bianchi2_sky_mod::out().
real(s2_dp),dimension(b2gd_nvars, b2gd_ntmax) bianchi2_globaldata_mod::b2gd_xarr
Definition at line 38 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::get_results(), and bianchi2_sky_mod::out().
real,dimension(b2gd_ntmax) bianchi2_globaldata_mod::b2gd_xreal
Definition at line 27 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::get_results().
real(s2_dp) bianchi2_globaldata_mod::b2gd_ze
Definition at line 35 of file bianchi2_globaldata_mod.f90.
Referenced by bianchi2_sky_mod::bianchi2_sky_init(), bianchi2_sky_mod::bianchi2_sky_init_alm(), and bianchi2_sky_mod::get_tau().