src/prog/bianchi2_lut_gen.f90 File Reference
bianchi2_lut_gen.f90 File Reference
Functions/Subroutines
program bianchi2_lut_gen
Generate a Look-Up-Table containing the values of the Legendre functions for a given couple (lmax,Ntheta).
subroutine parse_options
Parse the options passed when program called.
Function/Subroutine Documentation
program bianchi2_lut_gen ()
Generate a Look-Up-Table containing the values of the Legendre functions for a given couple (lmax,Ntheta).
Usage
bianchi2_lut_gen [-lmax lmax]
                 [-Ntheta Ntheta]
                 [-out filename_LUT]
Parameters
[in] lmax Maximum spherical harmonic order to consider.
[in] Ntheta Number of theta grid points to consider.
[in] out Filename of the output LUT.
Authors
Thibaut Josset
Definition at line 21 of file bianchi2_lut_gen.f90.
References bianchi2_lut_mod::bianchi2_lut_init(), bianchi2_lut_mod::bianchi2_lut_write(), and parse_options().
subroutine bianchi2_lut_gen::parse_options ()
Parse the options passed when program called.
Authors
Thibaut Josset
Definition at line 53 of file bianchi2_lut_gen.f90.
Referenced by bianchi2_lut_gen().