src/prog/bianchi2_sim.f90 File Reference
bianchi2_sim.f90 File Reference
Functions/Subroutines
program bianchi2_sim
Simulate a Bianchi2 VII_h model of the CMB, incorporating a cosmological constant.
Function/Subroutine Documentation
program bianchi2_sim ()
Simulate a Bianchi2 VII_h model of the CMB, incorporating a cosmological constant.
Usage
bianchi2_sim
bianchi2_sim param.par
Authors
Jason McEwen
Anthony Lasenby
Thibaut Josset
Definition at line 19 of file bianchi2_sim.f90.
References bianchi2_error_mod::bianchi2_error(), bianchi2_lut_mod::bianchi2_lut_free(), bianchi2_lut_mod::bianchi2_lut_read(), bianchi2_sky_mod::bianchi2_sky_apply_beam(), bianchi2_sky_mod::bianchi2_sky_compute_alm(), bianchi2_sky_mod::bianchi2_sky_compute_cl(), bianchi2_sky_mod::bianchi2_sky_compute_map(), bianchi2_sky_mod::bianchi2_sky_free(), bianchi2_sky_mod::bianchi2_sky_init(), bianchi2_sky_mod::bianchi2_sky_init_alm(), bianchi2_sky_mod::bianchi2_sky_param_write(), bianchi2_sky_mod::bianchi2_sky_rotate(), bianchi2_sky_mod::bianchi2_sky_write(), and bianchi2_sky_mod::bianchi2_sky_write_cl().