bianchi2_lut_mod Module Reference
bianchi2_lut_mod Module Reference
Lookup table for associated Legendre function for case where m=1. Also contains functionality to compute associated Legendre functions if a LUT is not used.
Data Types
type bianchi2_lut
Look-up-table that contains precomputed associated Legendre functions.
Public Member Functions
type(bianchi2_lut) function, public bianchi2_lut_init (lmax, Ntheta)
Initalizes a lut using lmax and Ntheta.
subroutine, public bianchi2_lut_write (lut, filename_LUT)
Writes a lut in a binary file.
type(bianchi2_lut) function, public bianchi2_lut_read (lmax, Ntheta, filename_LUT)
Reads a lut from a file.
real(s2_dp) function, public bianchi2_lut_access (lut, l, itheta)
Gives the value in the lut corresponding to a given (l,itheta).
subroutine, public bianchi2_lut_free (lut)
Deallocate the Look_Up_Table.
real(s2_dp) function, public bianchi2_lut_plgndr (l, m, x)
Computes the associated Legendre function for l and m. Adapted from numerical recipes.
Detailed Description
Lookup table for associated Legendre function for case where m=1. Also contains functionality to compute associated Legendre functions if a LUT is not used.
Note
Tailored to Bianchi2 code since input for associated Legendre function is theta not x.
Authors
Jason McEwen
Thibaut Josset
Definition at line 15 of file bianchi2_lut_mod.f90.
Member Function/Subroutine Documentation
real(s2_dp) function, public bianchi2_lut_mod::bianchi2_lut_access (type(bianchi2_lut), intent(in) lut, integer, intent(in) l, integer, intent(in) itheta)
Gives the value in the lut corresponding to a given (l,itheta).
Parameters
[in] lut Initialized bianchi2_lut object.
[in] l
[in] itheta
Return values
plm1 Value of the Lengendre functions contained in the lut.
Authors
Thibaut Josset
Definition at line 196 of file bianchi2_lut_mod.f90.
Referenced by bianchi2_sky_mod::bianchi2_sky_comp_ix().
subroutine, public bianchi2_lut_mod::bianchi2_lut_free (type(bianchi2_lut), intent(inout) lut)
Deallocate the Look_Up_Table.
Parameters
[in] lut Bianchi2_lut object to make free.
Authors
Thibaut Josset
Definition at line 216 of file bianchi2_lut_mod.f90.
Referenced by bianchi2_sim().
type(bianchi2_lut) function, public bianchi2_lut_mod::bianchi2_lut_init (integer, intent(in) lmax, integer, intent(in) Ntheta)
Initalizes a lut using lmax and Ntheta.
Parameters
[in] lmax Maximal harmonic to consider.
[in] Ntheta Number of points for theta.
Return values
lut Initialized bianchi2_lut object.
Authors
Thibaut Josset
Definition at line 71 of file bianchi2_lut_mod.f90.
References bianchi2_lut_plgndr().
Referenced by bianchi2_lut_gen().
real(s2_dp) function, public bianchi2_lut_mod::bianchi2_lut_plgndr (integer l, integer m, real(s2_dp) x)
Computes the associated Legendre function for l and m. Adapted from numerical recipes.
Note
Numerical recipies comment: Computes the associated Legendre polynomial P_m^l(x).
Parameters
[in] l Legendre function l parameter.
[in] m Legendre function m parameter.
[in] x Point to evaluate specified Legendre funtion at.
Authors
Jason McEwen
Definition at line 243 of file bianchi2_lut_mod.f90.
Referenced by bianchi2_lut_init(), and bianchi2_sky_mod::bianchi2_sky_comp_ix().
type(bianchi2_lut) function, public bianchi2_lut_mod::bianchi2_lut_read (integer, intent(in) lmax, integer, intent(in) Ntheta, character(len=s2_string_len) filename_LUT)
Reads a lut from a file.
Parameters
[in] lmax Maximum spherical harmonic l to consider.
[in] Ntheta Number of terms used to compute IA and IB.
[in] filename_LUT Name of binary file containing the LUT.
Return values
lut bianchi2_lut object to get.
Authors
Thibaut Josset
Definition at line 147 of file bianchi2_lut_mod.f90.
References bianchi2_error_mod::bianchi2_error().
Referenced by bianchi2_sim().
subroutine, public bianchi2_lut_mod::bianchi2_lut_write (type(bianchi2_lut), intent(in) lut, character(len=s2_string_len), intent(in) filename_LUT)
Writes a lut in a binary file.
Parameters
[in] lut Initialized bianchi2_lut object [in] filename_LUT Name of binary file containing the LUT.
Authors
Thibaut Josset
Definition at line 108 of file bianchi2_lut_mod.f90.
Referenced by bianchi2_lut_gen().
The documentation for this module was generated from the following file:
src/mod/bianchi2_lut_mod.f90