bianchi2_error_mod Module Reference
bianchi2_error_mod Module Reference
Functionality to handle errors that may occur in the bianchi2 library. Public bianchi2 error codes are defined, with corresponding private error comments and default halt execution status.
Public Member Functions
subroutine, public bianchi2_error (error_code, procedure, comment_add, comment_out, halt_in)
Display error message corresponding to error_code and halt program execution if required.
Public Attributes
integer, parameter, public bianchi2_error_none = 0
integer, parameter, public bianchi2_error_init = 1
integer, parameter, public bianchi2_error_not_init = 2
integer, parameter, public bianchi2_error_init_fail = 3
integer, parameter, public bianchi2_error_mem_alloc_fail = 4
integer, parameter, public bianchi2_error_sim_param_invalid = 5
integer, parameter, public bianchi2_error_sim_narg = 6
integer, parameter, public bianchi2_error_sky_num_fail = 7
integer, parameter, public bianchi2_error_tmplfit_fail = 8
integer, parameter, public bianchi2_error_plm1table_theta_invalid = 9
integer, parameter, public bianchi2_error_plm1table_l_invalid = 10
Private Attributes
integer, parameter bianchi2_error_num = 11
character(len=s2_string_len),
dimension(bianchi2_error_num),
parameter error_comment = (/ 'No error ', 'Attempt to initialise object that has already been initialised ', 'Object not initialised ', 'Object initialisation failed ', 'Memory allocation failed ', 'Invalid simulation parameter ', 'Invalid number of command line parameters ', 'Numerical routine failed ', 'Template fitting failed ', 'Invalid theta for Plm1 lookup table (not on regular grid) ', 'Invalid l for Plm1 lookup table (out of range) ' /)
logical, dimension(bianchi2_error_num),
parameter halt_default = (/ .false., .true., .true., .true., .true., .true., .true., .true., .true., .true., .true. /)
Default program halt status of each error type.
Detailed Description
Functionality to handle errors that may occur in the bianchi2 library. Public bianchi2 error codes are defined, with corresponding private error comments and default halt execution status.
Authors
Jason McEwen
Definition at line 11 of file bianchi2_error_mod.f90.
Member Function/Subroutine Documentation
subroutine, public bianchi2_error_mod::bianchi2_error (integer, intent(in) error_code, character(len=*), intent(in), optional procedure, character(len=*), intent(in), optional comment_add, character(len=*), intent(inout), optional comment_out, logical, intent(in), optional halt_in)
Display error message corresponding to error_code and halt program execution if required.
Parameters
[in] error_code Integer error code. [in] procedure Procedure name where bianchi2_error called from. Displayed when error message printed to screen.
[in] comment_add If present, additional comment to append to default error comment.
[in,out] comment_out If present the error comment is copied to comment_out on output.
[in] halt_in If present overrides default halt value.
Authors
Jason McEwen
Definition at line 106 of file bianchi2_error_mod.f90.
Referenced by bianchi2_lut_mod::bianchi2_lut_read(), bianchi2_sim(), bianchi2_sky_mod::bianchi2_sky_compute_alm(), bianchi2_sky_mod::bianchi2_sky_compute_cl(), bianchi2_sky_mod::bianchi2_sky_compute_map(), bianchi2_sky_mod::bianchi2_sky_free(), bianchi2_sky_mod::bianchi2_sky_get_alm(), bianchi2_sky_mod::bianchi2_sky_init(), bianchi2_sky_mod::bianchi2_sky_init_alm(), bianchi2_sky_mod::bianchi2_sky_rotate(), bianchi2_sky_mod::bianchi2_sky_write(), and bianchi2_sky_mod::get_results().
Member Data Documentation
integer, parameter, public bianchi2_error_mod::bianchi2_error_init = 1
Definition at line 33 of file bianchi2_error_mod.f90.
integer, parameter, public bianchi2_error_mod::bianchi2_error_init_fail = 3
Definition at line 33 of file bianchi2_error_mod.f90.
integer, parameter, public bianchi2_error_mod::bianchi2_error_mem_alloc_fail = 4
Definition at line 33 of file bianchi2_error_mod.f90.
integer, parameter, public bianchi2_error_mod::bianchi2_error_none = 0
Definition at line 33 of file bianchi2_error_mod.f90.
integer, parameter, public bianchi2_error_mod::bianchi2_error_not_init = 2
Definition at line 33 of file bianchi2_error_mod.f90.
integer, parameter bianchi2_error_mod::bianchi2_error_num = 11 private
Definition at line 31 of file bianchi2_error_mod.f90.
integer, parameter, public bianchi2_error_mod::bianchi2_error_plm1table_l_invalid = 10
Definition at line 33 of file bianchi2_error_mod.f90.
integer, parameter, public bianchi2_error_mod::bianchi2_error_plm1table_theta_invalid = 9
Definition at line 33 of file bianchi2_error_mod.f90.
integer, parameter, public bianchi2_error_mod::bianchi2_error_sim_narg = 6
Definition at line 33 of file bianchi2_error_mod.f90.
integer, parameter, public bianchi2_error_mod::bianchi2_error_sim_param_invalid = 5
Definition at line 33 of file bianchi2_error_mod.f90.
integer, parameter, public bianchi2_error_mod::bianchi2_error_sky_num_fail = 7
Definition at line 33 of file bianchi2_error_mod.f90.
integer, parameter, public bianchi2_error_mod::bianchi2_error_tmplfit_fail = 8
Definition at line 33 of file bianchi2_error_mod.f90.
character(len=s2_string_len), dimension(bianchi2_error_num), parameter bianchi2_error_mod::error_comment = (/ 'No error ', 'Attempt to initialise object that has already been initialised ', 'Object not initialised ', 'Object initialisation failed ', 'Memory allocation failed ', 'Invalid simulation parameter ', 'Invalid number of command line parameters ', 'Numerical routine failed ', 'Template fitting failed ', 'Invalid theta for Plm1 lookup table (not on regular grid) ', 'Invalid l for Plm1 lookup table (out of range) ' /) private
Definition at line 50 of file bianchi2_error_mod.f90.
logical, dimension(bianchi2_error_num), parameter bianchi2_error_mod::halt_default = (/ .false., .true., .true., .true., .true., .true., .true., .true., .true., .true., .true. /) private
Default program halt status of each error type.
Definition at line 67 of file bianchi2_error_mod.f90.
The documentation for this module was generated from the following file:
src/mod/bianchi2_error_mod.f90