bianchi2_sky_mod Module Reference
bianchi2_sky_mod Module Reference
Provides functionality to simulate a Bianchi2 VII_h model of the CMB, incorporating a cosmological constant. Uses the s2_sky module to create healpix sky maps.
Data Types
type bianchi2_sky
Bianchi 2 sky object that contains parameters and simulated sky.
Functions/Subroutines
type(bianchi2_sky), public bianchi2_sky_init (omega_matter_in, omega_lambda_in, h, zE_in, wH, rhand, nside)
Initialise bianchi2 object by performing a bianchi2 simulation that incorporates a cosmological constant.
type(bianchi2_sky), public bianchi2_sky_init_alm (omega_matter_in, omega_lambda_in, h, zE_in, wH, rhand, nside, lmax, Nuse, alpha, beta, gamma)
subroutine, public bianchi2_sky_free (b)
subroutine, public bianchi2_sky_param_write (b)
subroutine, public bianchi2_sky_compute_map (b, nside)
subroutine, public bianchi2_sky_compute_alm (b, lmax, mmax)
type(s2_sky), public bianchi2_sky_get_sky (b)
subroutine, public bianchi2_sky_get_alm (b, alm)
subroutine, public bianchi2_sky_apply_beam (b, fwhm, lmax)
subroutine, public bianchi2_sky_write (b, filename, file_type, comment)
subroutine, public bianchi2_sky_rotate (b, alpha, beta, gamma, lmax, nside, rotation_alm)
subroutine get_results (tstop_use, R_final, RH_final, cos_bit_final, sin_bit_final)
subroutine fcn (t, vars, ff)
subroutine out (t, vals)
subroutine get_tau (tau_needed)
real(s2_dp) F1r (a)
real(s2_dp) bianchi2_sky_comp_IX (l, Nuse, X_grid)
real(s2_dp) plgndr (l, m, x)
Variables
real(s2_dp), parameter BIANCHI2_CMB_T = 2.725d3
CMB T to convert Delta_T / T map to just Delta_T map.
Detailed Description
Provides functionality to simulate a Bianchi2 VII_h model of the CMB, incorporating a cosmological constant. Uses the s2_sky module to create healpix sky maps.
Authors:
Jason McEwen
Anthony Lasenby
Function/Subroutine Documentation
subroutine,public bianchi2_sky_mod::bianchi2_sky_apply_beam (type(bianchi2_sky),intent(inout) b, real(s2_sp),intent(in) fwhm, integer,intent(in) lmax)
Definition at line 844 of file bianchi2_sky_mod.f90.
Referenced by bianchi2_sim().
real(s2_dp) bianchi2_sky_mod::bianchi2_sky_comp_IX (integer,intent(in) l, integer,intent(in) Nuse, real(s2_dp),dimension(0:),intent(in) X_grid)
Definition at line 1332 of file bianchi2_sky_mod.f90.
References plgndr().
Referenced by bianchi2_sky_init_alm().
subroutine,public bianchi2_sky_mod::bianchi2_sky_compute_alm (type(bianchi2_sky),intent(inout) b, integer,intent(in) lmax, integer,intent(in) mmax)
Definition at line 731 of file bianchi2_sky_mod.f90.
References bianchi2_error_mod::bianchi2_error(), and bianchi2_error_mod::BIANCHI2_ERROR_NOT_INIT.
Referenced by bianchi2_sim(), and bianchi2_sky_rotate().
subroutine,public bianchi2_sky_mod::bianchi2_sky_compute_map (type(bianchi2_sky),intent(inout) b, integer,intent(in) nside)
Definition at line 696 of file bianchi2_sky_mod.f90.
References bianchi2_error_mod::bianchi2_error(), and bianchi2_error_mod::BIANCHI2_ERROR_NOT_INIT.
Referenced by bianchi2_sky_init_alm(), and bianchi2_sky_rotate().
subroutine,public bianchi2_sky_mod::bianchi2_sky_free (type(bianchi2_sky),intent(inout) b)
Definition at line 626 of file bianchi2_sky_mod.f90.
References bianchi2_error_mod::bianchi2_error(), and bianchi2_error_mod::BIANCHI2_ERROR_NOT_INIT.
Referenced by bianchi2_sim(), and bianchi2_sim_looptest().
subroutine,public bianchi2_sky_mod::bianchi2_sky_get_alm (type(bianchi2_sky),intent(in) b, complex(s2_spc),dimension(:,:),intent(out) alm)
Definition at line 806 of file bianchi2_sky_mod.f90.
References bianchi2_error_mod::bianchi2_error(), and bianchi2_error_mod::BIANCHI2_ERROR_NOT_INIT.
Referenced by bianchi2_sky_rotate().
type(s2_sky),public bianchi2_sky_mod::bianchi2_sky_get_sky (type(bianchi2_sky),intent(in) b)
Definition at line 769 of file bianchi2_sky_mod.f90.
References bianchi2_error_mod::BIANCHI2_ERROR_NOT_INIT.
type(bianchi2_sky),public bianchi2_sky_mod::bianchi2_sky_init (real(s2_dp),intent(in) omega_matter_in, real(s2_dp),intent(in) omega_lambda_in, real(s2_dp),intent(in) h, real(s2_dp),intent(in) zE_in, real(s2_dp),intent(in) wH, logical,intent(in) rhand, integer,intent(in) nside)
Initialise bianchi2 object by performing a bianchi2 simulation that incorporates a cosmological constant.
Variables:
Parameters:
[in] omega_matter_in Input omega_matter parameter (see bianchi2 data type for explanation).
[in] omega_lambda_in Input omega_lambda parameter (see bianchi2 data type for explanation).
[in] h Input h parameter (see bianchi2 data type for explanation).
[in] zE_in Input zE parameter (see bianchi2 data type for explanation).
[in] wH Input wH parameter (see bianchi2 data type for explanation).
[in] rhand Logical to specify handedness of map.
[in] nside Nside of Healpix map to generate.
Return values:
b Initialised bianchi2 object with simulated map calculated.
Authors:
Jason McEwen
Anthony Lasenby
Definition at line 141 of file bianchi2_sky_mod.f90.
References bianchi2_globaldata_mod::b2gd_alpha, bianchi2_globaldata_mod::b2gd_Bianchi_h, bianchi2_globaldata_mod::b2gd_Omega_Lambda, bianchi2_globaldata_mod::b2gd_Omega_matter, bianchi2_globaldata_mod::b2gd_phi_0, bianchi2_globaldata_mod::b2gd_RH_start, bianchi2_globaldata_mod::b2gd_theta_0, bianchi2_globaldata_mod::b2gd_ze, BIANCHI2_CMB_T, bianchi2_error_mod::bianchi2_error(), bianchi2_error_mod::BIANCHI2_ERROR_INIT, bianchi2_error_mod::BIANCHI2_ERROR_MEM_ALLOC_FAIL, get_results(), and get_tau().
Referenced by bianchi2_sim(), and bianchi2_sim_looptest().
type(bianchi2_sky),public bianchi2_sky_mod::bianchi2_sky_init_alm (real(s2_dp),intent(in) omega_matter_in, real(s2_dp),intent(in) omega_lambda_in, real(s2_dp),intent(in) h, real(s2_dp),intent(in) zE_in, real(s2_dp),intent(in) wH, logical,intent(in) rhand, integer,intent(in) nside, integer,intent(in) lmax, integer,intent(in) Nuse, real(s2_sp),intent(in),optional alpha, real(s2_sp),intent(in),optional beta, real(s2_sp),intent(in),optional gamma)
Definition at line 365 of file bianchi2_sky_mod.f90.
References bianchi2_globaldata_mod::b2gd_alpha, bianchi2_globaldata_mod::b2gd_Bianchi_h, bianchi2_globaldata_mod::b2gd_Omega_Lambda, bianchi2_globaldata_mod::b2gd_Omega_matter, bianchi2_globaldata_mod::b2gd_RH_start, bianchi2_globaldata_mod::b2gd_theta_0, bianchi2_globaldata_mod::b2gd_ze, BIANCHI2_CMB_T, bianchi2_error_mod::bianchi2_error(), bianchi2_error_mod::BIANCHI2_ERROR_INIT, bianchi2_error_mod::BIANCHI2_ERROR_MEM_ALLOC_FAIL, bianchi2_sky_comp_IX(), bianchi2_sky_compute_map(), get_results(), and get_tau().
Referenced by bianchi2_sim().
subroutine,public bianchi2_sky_mod::bianchi2_sky_param_write (type(bianchi2_sky),intent(in) b)
Definition at line 665 of file bianchi2_sky_mod.f90.
Referenced by bianchi2_sim().
subroutine,public bianchi2_sky_mod::bianchi2_sky_rotate (type(bianchi2_sky),intent(inout) b, real(s2_sp),intent(in),optional alpha, real(s2_sp),intent(in),optional beta, real(s2_sp),intent(in),optional gamma, integer,intent(in) lmax, integer,intent(in) nside, logical,intent(in) rotation_alm)
Definition at line 944 of file bianchi2_sky_mod.f90.
References bianchi2_error_mod::bianchi2_error(), bianchi2_error_mod::BIANCHI2_ERROR_MEM_ALLOC_FAIL, bianchi2_error_mod::BIANCHI2_ERROR_NOT_INIT, bianchi2_sky_compute_alm(), bianchi2_sky_compute_map(), and bianchi2_sky_get_alm().
Referenced by bianchi2_sim().
subroutine,public bianchi2_sky_mod::bianchi2_sky_write (type(bianchi2_sky),intent(inout) b, character(len=*),intent(in) filename, integer,intent(in) file_type, character(len=*),intent(in),optional comment)
Definition at line 891 of file bianchi2_sky_mod.f90.
References bianchi2_error_mod::bianchi2_error(), and bianchi2_error_mod::BIANCHI2_ERROR_NOT_INIT.
Referenced by bianchi2_sim().
real(s2_dp) bianchi2_sky_mod::F1r (real(s2_dp),intent(in) a)
Definition at line 1289 of file bianchi2_sky_mod.f90.
References bianchi2_globaldata_mod::b2gd_alpha, bianchi2_globaldata_mod::b2gd_Omega_Lambda, and bianchi2_globaldata_mod::b2gd_Omega_matter.
Referenced by get_tau().
subroutine bianchi2_sky_mod::fcn (real(s2_dp),intent(in) t, real(s2_dp),dimension(nvars),intent(in) vars, real(s2_dp),dimension(nvars),intent(out) ff)
Definition at line 1149 of file bianchi2_sky_mod.f90.
References bianchi2_globaldata_mod::b2gd_alpha, bianchi2_globaldata_mod::b2gd_Omega_Lambda, bianchi2_globaldata_mod::b2gd_RH_start, and bianchi2_globaldata_mod::b2gd_theta_0.
Referenced by get_results(), and out().
subroutine bianchi2_sky_mod::get_results (real(s2_dp),intent(in) tstop_use, real(s2_dp),intent(out) R_final, real(s2_dp),intent(out) RH_final, real(s2_dp),intent(out) cos_bit_final, real(s2_dp),intent(out) sin_bit_final)
Definition at line 1055 of file bianchi2_sky_mod.f90.
References bianchi2_globaldata_mod::b2gd_deltat, bianchi2_globaldata_mod::b2gd_it, bianchi2_globaldata_mod::b2gd_nt, bianchi2_globaldata_mod::b2gd_RH_start, bianchi2_globaldata_mod::b2gd_tarr, bianchi2_globaldata_mod::b2gd_treal, bianchi2_globaldata_mod::b2gd_tstop, bianchi2_globaldata_mod::b2gd_xarr, bianchi2_globaldata_mod::b2gd_xreal, bianchi2_error_mod::bianchi2_error(), bianchi2_error_mod::BIANCHI2_ERROR_SKY_NUM_FAIL, fcn(), and out().
Referenced by bianchi2_sky_init(), and bianchi2_sky_init_alm().
subroutine bianchi2_sky_mod::get_tau (real(s2_dp),intent(out) tau_needed)
Definition at line 1240 of file bianchi2_sky_mod.f90.
References bianchi2_globaldata_mod::b2gd_ze, and F1r().
Referenced by bianchi2_sky_init(), and bianchi2_sky_init_alm().
subroutine bianchi2_sky_mod::out (real(s2_dp),intent(inout) t, real(s2_dp),dimension(b2gd_nvars),intent(in) vals)
Definition at line 1203 of file bianchi2_sky_mod.f90.
References bianchi2_globaldata_mod::b2gd_deltat, bianchi2_globaldata_mod::b2gd_it, bianchi2_globaldata_mod::b2gd_nt, bianchi2_globaldata_mod::b2gd_tarr, bianchi2_globaldata_mod::b2gd_tstop, bianchi2_globaldata_mod::b2gd_xarr, and fcn().
Referenced by get_results().
real(s2_dp) bianchi2_sky_mod::plgndr (integer l, integer m, real(s2_dp) x) [private]
Definition at line 1386 of file bianchi2_sky_mod.f90.
Referenced by bianchi2_sky_comp_IX().
Variable Documentation
real(s2_dp),parameter bianchi2_sky_mod::BIANCHI2_CMB_T = 2.725d3
CMB T to convert Delta_T / T map to just Delta_T map.
Definition at line 77 of file bianchi2_sky_mod.f90.
Referenced by bianchi2_sky_init(), and bianchi2_sky_init_alm().